// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_gP9WREBMUCc9VDpLQUyAwq7mGgzzoBs',
    appId: '1:330727299335:web:8ee7c1395716dde2d38da2',
    messagingSenderId: '330727299335',
    projectId: 'gofund-3805a',
    authDomain: 'gofund-3805a.firebaseapp.com',
    storageBucket: 'gofund-3805a.appspot.com',
    measurementId: 'G-58J8779863',
    databaseURL: "https://gofund-3805a-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj28OmTbFQ9uCpm4HmCA681la07q8uzgg',
    appId: '1:330727299335:android:15efc30ce3b777e5d38da2',
    messagingSenderId: '330727299335',
    projectId: 'gofund-3805a',
    storageBucket: 'gofund-3805a.appspot.com',
    databaseURL: "https://gofund-3805a-default-rtdb.firebaseio.com",
    authDomain: "gofund-3805a.firebaseapp.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfQ4NK2FA5J46_Wj-j0Btq6rVOkFR7ui8',
    appId: '1:330727299335:ios:dafa658391bb7651d38da2',
    messagingSenderId: '330727299335',
    projectId: 'gofund-3805a',
    storageBucket: 'gofund-3805a.appspot.com',
    iosClientId: '330727299335-od6i66tmknts3pemjkogo8au80nk18tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.charity',
    databaseURL: "https://gofund-3805a-default-rtdb.firebaseio.com",
    authDomain: "gofund-3805a.firebaseapp.com",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfQ4NK2FA5J46_Wj-j0Btq6rVOkFR7ui8',
    appId: '1:330727299335:ios:5f643dc6d7856102d38da2',
    messagingSenderId: '330727299335',
    projectId: 'gofund-3805a',
    storageBucket: 'gofund-3805a.appspot.com',
    iosClientId: '330727299335-8tqntfn54pc8sev5mdv46h22hl82vmth.apps.googleusercontent.com',
    iosBundleId: 'com.example.charity.RunnerTests',
    databaseURL: "https://gofund-3805a-default-rtdb.firebaseio.com",
    authDomain: "gofund-3805a.firebaseapp.com",
  );
}
